//============================================================================================================================================
//  PRESETS.JS — GEOLOGICAL TERRAIN LAYER TYPES, SATMAP COLOR RAMPS, TEXTURE LAYER TEMPLATES & 8 AAA WORLD PRESETS
//  Upgraded with Lagrangian Particle-Droplet Hydraulic Erosion, Sheer Cliffs, Rugged Outcrops, 3D Boulder Fields & Stratification
//============================================================================================================================================

export const SATMAPS = [
  {
    id: "granite_gneiss",
    name: "Alpine Granite & Dark Gneiss",
    category: "Bedrock",
    stops: ["#16191d", "#2c3138", "#4a525d", "#737c87", "#a5aeb8"],
  },
  {
    id: "dolomite_limestone",
    name: "Dolomite Pale Cliff Limestone",
    category: "Bedrock",
    stops: ["#2c2a28", "#54504b", "#857e75", "#b8b0a4", "#e3dcd0"],
  },
  {
    id: "colorado_sandstone",
    name: "Colorado Red Canyon Sandstone",
    category: "Strata",
    stops: ["#38160e", "#6e2b1b", "#a6482a", "#cf7446", "#ebb07c"],
  },
  {
    id: "utah_badlands",
    name: "Utah Badlands Banded Shale",
    category: "Strata",
    stops: ["#36231e", "#693e34", "#9c6b58", "#c4a289", "#e3d2be"],
  },
  {
    id: "iceland_basalt",
    name: "Icelandic Columnar Basalt",
    category: "Bedrock",
    stops: ["#0e1013", "#1c2026", "#2f353d", "#485059", "#69737d"],
  },
  {
    id: "talus_scree",
    name: "Angular Boulders & Slate Scree",
    category: "Sediment",
    stops: ["#242220", "#423e39", "#665f56", "#8c8377", "#b2a89a"],
  },
  {
    id: "alluvial_silt",
    name: "Alluvial Fan Gravel & Silt",
    category: "Sediment",
    stops: ["#22201c", "#3f3a32", "#635c4e", "#8c816d", "#b5a992"],
  },
  {
    id: "iceland_moss",
    name: "Highland Rhyolite & Lichen Moss",
    category: "Biome",
    stops: ["#1e2612", "#384a1f", "#58732c", "#7d963b", "#a6b858"],
  },
  {
    id: "subalpine_meadow",
    name: "Sub-Alpine Meadow & Turf",
    category: "Biome",
    stops: ["#162412", "#28401e", "#3f5e2d", "#5d7d40", "#829c5c"],
  },
  {
    id: "scottish_heather",
    name: "Highland Peat & Heather Moor",
    category: "Biome",
    stops: ["#211814", "#3b2b21", "#573f2e", "#70543a", "#8a6e4c"],
  },
  {
    id: "sahara_erg",
    name: "Aeolian Golden Silica Sand",
    category: "Sediment",
    stops: ["#613f22", "#8f6137", "#ba8750", "#dba972", "#f2daa8"],
  },
  {
    id: "coastal_sand",
    name: "Braided Riverbed & Wet Cobble",
    category: "Sediment",
    stops: ["#332e26", "#544b3e", "#7d715e", "#ab9d85", "#d4c8b0"],
  },
  {
    id: "volcanic_sulfur",
    name: "Hydrothermal Ash & Sulfur Crust",
    category: "Strata",
    stops: ["#171613", "#363327", "#665e3b", "#9e8f4b", "#d1bf66"],
  },
  {
    id: "glacial_snow",
    name: "Fresh Alpine Powder & Firn",
    category: "Snow/Ice",
    stops: ["#94a9bf", "#b5c8db", "#d4e2ee", "#ebf2f9", "#ffffff"],
  },
  {
    id: "glacial_ice",
    name: "Glacial Serac & Blue Crevasse Ice",
    category: "Snow/Ice",
    stops: ["#183d59", "#2c648c", "#5091ba", "#88bfe0", "#cae8fa"],
  },
  {
    id: "emerald_sediment",
    name: "Glacial Rock Flour & Riverbed",
    category: "Sediment",
    stops: ["#192e30", "#294b4d", "#416e6e", "#64948f", "#93bdb5"],
  },
];

export const BLEND_MODES = [
  { id: 0, name: "Add", short: "ADD" },
  { id: 1, name: "Subtract", short: "SUB" },
  { id: 2, name: "Multiply", short: "MUL" },
  { id: 3, name: "Max (Union)", short: "MAX" },
  { id: 4, name: "Min (Intersect)", short: "MIN" },
  { id: 5, name: "Mix (Lerp)", short: "MIX" },
  { id: 6, name: "Screen", short: "SCR" },
  { id: 7, name: "Amplify", short: "AMP" },
];

export const TEX_BLEND_MODES = [
  { id: 0, name: "Height-Mask Rock Blend", short: "HGT" },
  { id: 1, name: "Standard Alpha Mix", short: "MIX" },
  { id: 2, name: "Multiply Tint", short: "MUL" },
  { id: 3, name: "Overlay Detail", short: "OVL" },
  { id: 4, name: "Max Priority", short: "MAX" },
];

export const TERRAIN_LAYER_TYPES = {
  mountain_range: {
    type: "mountain_range",
    name: "Tectonic Mountain Range",
    category: "Base Landforms",
    icon: "terrain.svg",
    color: "#c89d66",
    isSimulation: false,
    description:
      "Anisotropic ridged multifractal massif with Jordan/Swiss analytical derivative damping, sheer cliff escarpments, and glaciated U-valleys.",
    defaults: {
      blendMode: 0,
      opacity: 1.0,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 104,
      elevation: 1950,
      scale: 2.35,
      octaves: 8,
      lacunarity: 2.12,
      gain: 0.5,
      ridgeSharpness: 1.65,
      cliffSteepness: 0.65,
      strikeAngle: 34,
      anisotropy: 0.42,
      valleyFloor: 0.42,
      warpStrength: 0.48,
      offsetX: 0.0,
      offsetZ: 0.0,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  alpine_peak: {
    type: "alpine_peak",
    name: "Alpine Glacial Horn",
    category: "Base Landforms",
    icon: "terrain.svg",
    color: "#e0b379",
    isSimulation: false,
    description:
      "Pyramidal Matterhorn-class glacial horn with knife-edge arête ridges, concave cirque headwalls, and sheer stepped rock faces.",
    defaults: {
      blendMode: 3, // Max
      opacity: 1.0,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 217,
      elevation: 2420,
      scale: 2.15,
      octaves: 8,
      lacunarity: 2.15,
      gain: 0.5,
      ridgeSharpness: 1.85,
      areteCount: 4,
      cirqueCarving: 0.68,
      cliffSteepness: 0.72,
      radiusKm: 2.2,
      warpStrength: 0.4,
      offsetX: 0.0,
      offsetZ: 0.0,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 90,
      maskRadial: 0.4,
    },
  },

  canyon_mesa: {
    type: "canyon_mesa",
    name: "Canyon & Mesa Plateau",
    category: "Base Landforms",
    icon: "terrain.svg",
    color: "#cc6b49",
    isSimulation: false,
    description:
      "Stepped Colorado-class sandstone plateau incised by a meandering primary river gorge, sheer vertical cliff walls, and dendritic side-canyons.",
    defaults: {
      blendMode: 0,
      opacity: 1.0,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 309,
      elevation: 1650,
      scale: 1.9,
      octaves: 8,
      canyonDepth: 0.85,
      canyonWidth: 0.3,
      meanderFreq: 1.75,
      stepCount: 7,
      stepSharpness: 0.82,
      warpStrength: 0.45,
      offsetX: 0.0,
      offsetZ: 0.0,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  volcano: {
    type: "volcano",
    name: "Volcanic Caldera & Cone",
    category: "Base Landforms",
    icon: "terrain.svg",
    color: "#d95f43",
    isSimulation: false,
    description:
      "Composite stratovolcano cone with collapsed summit caldera ringwall, deep radial pyroclastic lahar gullies, and basaltic dike outcrops.",
    defaults: {
      blendMode: 3,
      opacity: 1.0,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 412,
      elevation: 2150,
      radiusKm: 2.35,
      calderaRadius: 0.36,
      calderaDepth: 0.68,
      radialGullies: 22,
      gullyDepth: 0.58,
      breachAngle: 125,
      breachStrength: 0.45,
      warpStrength: 0.36,
      offsetX: 0.0,
      offsetZ: 0.0,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 90,
      maskRadial: 0.25,
    },
  },

  fault_scarp: {
    type: "fault_scarp",
    name: "Sheer Cliffs & Tectonic Faults",
    category: "Geological Structure",
    icon: "collection-stacked-layers.svg",
    color: "#b38f68",
    isSimulation: false,
    description:
      "Carves near-vertical tectonic fault escarpments, fractured Voronoi rock blocks, and tilted horst/graben cliff walls.",
    defaults: {
      blendMode: 0,
      opacity: 0.9,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 518,
      elevation: 540,
      strikeAngle: 58,
      faultSharpness: 0.86,
      blockScale: 3.2,
      tiltAmount: 0.55,
      warpStrength: 0.52,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  strata: {
    type: "strata",
    name: "Folded Sedimentary Stratification",
    category: "Geological Structure",
    icon: "collection-stacked-layers.svg",
    color: "#d48a59",
    isSimulation: false,
    description:
      "Sculpts pronounced 3D sedimentary rock bedding planes and stepped cliff ledges that outcrop sharply across steep slopes and canyon walls.",
    defaults: {
      blendMode: 0,
      opacity: 0.88,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 612,
      elevation: 310,
      frequency: 16.0,
      dipAngle: 12,
      strikeAngle: 38,
      ledgeSharpness: 0.84,
      foldWarp: 0.38,
      maskAltMin: 40,
      maskAltMax: 3800,
      maskSlopeMin: 14,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  swiss_fbm: {
    type: "swiss_fbm",
    name: "Rugged Outcrops & Crags",
    category: "Geological Structure",
    icon: "terrain.svg",
    color: "#9aa8b8",
    isSimulation: false,
    description:
      "Injects jagged Voronoi rock outcrops, monolithic tors, and fractured crag spires that protrude through ridges and steep cliff faces.",
    defaults: {
      blendMode: 0,
      opacity: 0.92,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 733,
      elevation: 420,
      scale: 5.4,
      octaves: 7,
      lacunarity: 2.2,
      gain: 0.52,
      ridgeSharpness: 1.85,
      outcropDensity: 0.72,
      gradientDamping: 0.65,
      warpStrength: 0.4,
      maskAltMin: 80,
      maskAltMax: 4500,
      maskSlopeMin: 12,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  terrace: {
    type: "terrace",
    name: "Stepped Cliff Terracing",
    category: "Surface Modifiers",
    icon: "collection-stacked-layers.svg",
    color: "#b89f72",
    isSimulation: false,
    description:
      "Quantizes elevation into sharp geological cliff benches and flat caprock shelves with organic fracture modulation.",
    defaults: {
      blendMode: 5, // Mix
      opacity: 0.58,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 804,
      stepCount: 11,
      stepSharpness: 0.78,
      warpStrength: 0.35,
      slopePreservation: 0.55,
      maskAltMin: 0,
      maskAltMax: 3600,
      maskSlopeMin: 8,
      maskSlopeMax: 85,
      maskRadial: 0.0,
    },
  },

  dune_sea: {
    type: "dune_sea",
    name: "Aeolian Sand Dunes",
    category: "Base Landforms",
    icon: "wind.svg",
    color: "#dfb06b",
    isSimulation: false,
    description:
      "Wind-sculpted barchan and transverse dune fields with razor-sharp slip-face crests, windward ripples, and interdune corridors.",
    defaults: {
      blendMode: 0,
      opacity: 0.92,
      invert: false,
      domainWarp: true,
      maskLock: false,
      seed: 915,
      elevation: 340,
      scale: 5.2,
      windAngle: 48,
      crestSharpness: 1.75,
      asymmetry: 0.65,
      rippleDetail: 0.42,
      warpStrength: 0.46,
      maskAltMin: -200,
      maskAltMax: 1600,
      maskSlopeMin: 0,
      maskSlopeMax: 38,
      maskRadial: 0.0,
    },
  },

  hydraulic_erosion: {
    type: "hydraulic_erosion",
    name: "Hydraulic Erosion (Droplet + Pipe)",
    category: "Physical Erosion",
    icon: "weather-rain.svg",
    color: "#4da3ff",
    isSimulation: true,
    description:
      "Hybrid Lagrangian Particle-Droplet & Stream-Power Solver. Traces tens of thousands of sub-cell water droplets with inertia to carve deep, branching dendritic gullies, ravines, and braided alluvial fans.",
    defaults: {
      blendMode: 5,
      opacity: 1.0,
      invert: false,
      domainWarp: true,
      maskLock: false,
      iterations: 85,
      dropletCountK: 120, // 75,000 Lagrangian droplets!
      rainRate: 0.022,
      erosionRate: 0.78,
      depositionRate: 0.52,
      sedimentCapacity: 1.65,
      evaporation: 0.028,
      channelSharpness: 0.85,
      gullyDepth: 0.82,
      inertia: 0.28,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  thermal_erosion: {
    type: "thermal_erosion",
    name: "Thermal Talus & Boulders",
    category: "Physical Erosion",
    icon: "terrain.svg",
    color: "#e59a54",
    isSimulation: true,
    description:
      "Simulates freeze-thaw cliff spalling, conical talus scree aprons at the angle of repose, and 3D angular boulder fields settled at cliff bases and gullies.",
    defaults: {
      blendMode: 5,
      opacity: 1.0,
      invert: false,
      domainWarp: false,
      maskLock: false,
      iterations: 40,
      reposeAngle: 35,
      weatheringRate: 0.62,
      talusSpread: 0.75,
      boulderDensity: 0.78,
      boulderScale: 1.25,
      maskAltMin: -500,
      maskAltMax: 4500,
      maskSlopeMin: 18,
      maskSlopeMax: 90,
      maskRadial: 0.0,
    },
  },

  snowfall: {
    type: "snowfall",
    name: "Glacial Snowfall & Avalanche",
    category: "Physical Erosion",
    icon: "weather-snow.svg",
    color: "#b8dcff",
    isSimulation: true,
    description:
      "Physical snowpack & firn accumulation solver with altitude snowline, prevailing wind drift, south-aspect solar ablation, and avalanche slumping into couloirs.",
    defaults: {
      blendMode: 0,
      opacity: 1.0,
      invert: false,
      domainWarp: true,
      maskLock: false,
      snowlineAlt: 1050,
      snowDepth: 0.75,
      reposeAngle: 43,
      windAzimuth: 310,
      windDrift: 0.52,
      solarMelt: 0.42,
      avalancheSlump: 0.68,
      maskAltMin: 400,
      maskAltMax: 4500,
      maskSlopeMin: 0,
      maskSlopeMax: 65,
      maskRadial: 0.0,
    },
  },
};

export function createTextureLayer(overrides = {}) {
  return Object.assign(
    {
      id: "tex_" + Math.random().toString(36).slice(2, 8),
      name: "Granite Bedrock",
      category: "Bedrock",
      enabled: true,
      solo: false,
      blendMode: 0,
      opacity: 1.0,
      heightContrast: 0.72,
      satmapId: "granite_gneiss",
      useSatmap: true,
      colPrimary: "#555b63",
      colSecondary: "#22262b",
      colAccent: "#929aa3",
      roughness: 0.78,
      specular: 0.35,
      detailScale: 16.0,
      normalStrength: 0.85,
      strataIntensity: 0.45,
      boulderDetail: 0.5,
      triplanar: true,
      microDetail: true,

      // Procedural Masks
      useAltMask: false,
      altMin: 0,
      altMax: 3500,
      altFeather: 200,
      altInvert: false,

      useSlopeMask: false,
      slopeMin: 0,
      slopeMax: 90,
      slopeFeather: 7,
      slopeInvert: false,

      useCurvatureMask: false,
      curvatureMode: 0, // 0 = Convex Ridges/Outcrops, 1 = Concave Gullies/Crevices
      curvatureStrength: 0.7,

      useFlowMask: false,
      flowStrength: 0.8,

      useSedimentMask: false,
      sedimentWeight: 0.8,
      talusWeight: 0.8,

      useSnowMask: false,
      snowWeight: 0.92,

      useNoiseMask: false,
      noiseScale: 5.0,
      noiseAmount: 0.35,
    },
    overrides
  );
}

export const TEXTURE_LAYER_TEMPLATES = [
  {
    templateId: "base_granite",
    name: "Alpine Granite & Gneiss Bedrock",
    category: "Bedrock & Cliffs",
    satmapId: "granite_gneiss",
    description: "Deep crystalline granite and dark metamorphic gneiss base rock with Voronoi joint fractures.",
    overrides: {
      name: "Alpine Granite Bedrock",
      category: "Bedrock",
      satmapId: "granite_gneiss",
      colPrimary: "#585f68",
      colSecondary: "#1e2227",
      colAccent: "#939ca6",
      roughness: 0.8,
      detailScale: 16.0,
      strataIntensity: 0.4,
    },
  },
  {
    templateId: "cliff_strata",
    name: "Sheer Cliff Stratification & Outcrops",
    category: "Bedrock & Cliffs",
    satmapId: "dolomite_limestone",
    description: "Targets steep cliffs and rugged outcrops with crisp sedimentary bedding bands and fracture ledges.",
    overrides: {
      name: "Sheer Cliff Stratification",
      category: "Cliffs",
      satmapId: "dolomite_limestone",
      colPrimary: "#8f887e",
      colSecondary: "#33302d",
      colAccent: "#cfc7ba",
      roughness: 0.72,
      strataIntensity: 0.88,
      useSlopeMask: true,
      slopeMin: 28,
      slopeMax: 90,
      slopeFeather: 7,
      useCurvatureMask: true,
      curvatureMode: 0,
      curvatureStrength: 0.62,
    },
  },
  {
    templateId: "red_sandstone",
    name: "Red Canyon Stratified Sandstone",
    category: "Bedrock & Cliffs",
    satmapId: "colorado_sandstone",
    description: "Iron-oxide banded Colorado sandstone with pronounced horizontal bedding and desert varnish.",
    overrides: {
      name: "Red Canyon Sandstone",
      category: "Strata",
      satmapId: "colorado_sandstone",
      colPrimary: "#b85635",
      colSecondary: "#451c12",
      colAccent: "#e6a370",
      roughness: 0.75,
      strataIntensity: 0.92,
    },
  },
  {
    templateId: "talus_apron",
    name: "Boulder Fields & Talus Scree",
    category: "Sediment & Talus",
    satmapId: "talus_scree",
    description: "Masks onto thermally weathered talus cones and cliff-base boulder fields with 3D rock normal facets.",
    overrides: {
      name: "Boulder Fields & Talus Scree",
      category: "Sediment",
      satmapId: "talus_scree",
      colPrimary: "#787066",
      colSecondary: "#33302b",
      colAccent: "#a69c8e",
      roughness: 0.86,
      boulderDetail: 0.9,
      detailScale: 24.0,
      useSedimentMask: true,
      sedimentWeight: 0.45,
      talusWeight: 0.95,
      useSlopeMask: true,
      slopeMin: 12,
      slopeMax: 45,
      slopeFeather: 7,
    },
  },
  {
    templateId: "alluvial_sediment",
    name: "Alluvial Outwash & Gravel Fans",
    category: "Sediment & Talus",
    satmapId: "alluvial_silt",
    description: "Targets eroded sediment deposits in valley floors, outwash plains, and braided alluvial fans.",
    overrides: {
      name: "Alluvial Outwash & Gravel",
      category: "Sediment",
      satmapId: "alluvial_silt",
      colPrimary: "#877c69",
      colSecondary: "#3d3830",
      colAccent: "#b3a792",
      roughness: 0.84,
      useSedimentMask: true,
      sedimentWeight: 0.95,
      talusWeight: 0.35,
      useSlopeMask: true,
      slopeMin: 0,
      slopeMax: 32,
      slopeFeather: 7,
    },
  },
  {
    templateId: "river_channels",
    name: "Erosion Gullies & Wet Riverbed",
    category: "Hydrology & Channels",
    satmapId: "emerald_sediment",
    description: "Highlights dendritic hydraulic erosion gullies and river channels with wet dark cobbles and specular sheen.",
    overrides: {
      name: "Erosion Gullies & Wet Cobble",
      category: "Hydrology",
      satmapId: "emerald_sediment",
      colPrimary: "#3e5c5c",
      colSecondary: "#182425",
      colAccent: "#7ea8a3",
      roughness: 0.28,
      specular: 0.72,
      useFlowMask: true,
      flowStrength: 0.92,
    },
  },
  {
    templateId: "alpine_meadow",
    name: "Sub-Alpine Meadow & Turf",
    category: "Vegetation & Biome",
    satmapId: "subalpine_meadow",
    description: "Colonizes gentle lower-to-mid elevation benches and moisture-retaining valleys with organic breakup.",
    overrides: {
      name: "Sub-Alpine Meadow & Turf",
      category: "Biome",
      satmapId: "subalpine_meadow",
      colPrimary: "#4d6b37",
      colSecondary: "#1f3016",
      colAccent: "#7d9656",
      roughness: 0.88,
      useAltMask: true,
      altMin: 90,
      altMax: 1180,
      altFeather: 200,
      useSlopeMask: true,
      slopeMin: 0,
      slopeMax: 31,
      slopeFeather: 7,
      useNoiseMask: true,
      noiseScale: 6.0,
      noiseAmount: 0.36,
    },
  },
  {
    templateId: "icelandic_moss",
    name: "Icelandic Highland Lichen Moss",
    category: "Vegetation & Biome",
    satmapId: "iceland_moss",
    description: "Vibrant Nordic chartreuse moss blanketing volcanic basalt benches and canyon shelves.",
    overrides: {
      name: "Highland Lichen & Moss",
      category: "Biome",
      satmapId: "iceland_moss",
      colPrimary: "#6c8534",
      colSecondary: "#283413",
      colAccent: "#a4b856",
      roughness: 0.9,
      useSlopeMask: true,
      slopeMin: 3,
      slopeMax: 36,
      slopeFeather: 8,
      useNoiseMask: true,
      noiseScale: 6.5,
      noiseAmount: 0.4,
    },
  },
  {
    templateId: "glacial_snowpack",
    name: "Alpine Snowpack & Couloir Firn",
    category: "Snow & Glacial Ice",
    satmapId: "glacial_snow",
    description: "Binds to physical simulated snow depth and high-altitude ridges with sharp rock outcrop protrusion.",
    overrides: {
      name: "Alpine Snowpack & Firn",
      category: "Snow/Ice",
      satmapId: "glacial_snow",
      colPrimary: "#f4f8fd",
      colSecondary: "#a5bcd4",
      colAccent: "#ffffff",
      roughness: 0.38,
      specular: 0.62,
      heightContrast: 0.84,
      useSnowMask: true,
      snowWeight: 0.95,
      useAltMask: true,
      altMin: 920,
      altMax: 4500,
      altFeather: 220,
      useSlopeMask: true,
      slopeMin: 0,
      slopeMax: 48,
      slopeFeather: 9,
    },
  },
  {
    templateId: "crevasse_ice",
    name: "Blue Glacial Serac Ice",
    category: "Snow & Glacial Ice",
    satmapId: "glacial_ice",
    description: "Translucent cerulean glacial ice exposed in steep high-altitude cirques and concave erosion gullies.",
    overrides: {
      name: "Blue Glacial Serac Ice",
      category: "Snow/Ice",
      satmapId: "glacial_ice",
      colPrimary: "#6ca6cc",
      colSecondary: "#224f70",
      colAccent: "#c7e7fa",
      roughness: 0.22,
      specular: 0.8,
      useAltMask: true,
      altMin: 1050,
      altMax: 4500,
      altFeather: 180,
      useCurvatureMask: true,
      curvatureMode: 1,
      curvatureStrength: 0.75,
    },
  },
];

export function createTerrainLayer(type, overrides = {}) {
  const schema = TERRAIN_LAYER_TYPES[type] || TERRAIN_LAYER_TYPES.mountain_range;
  return Object.assign(
    {
      id: "ter_" + Math.random().toString(36).slice(2, 8),
      type: schema.type,
      name: schema.name,
      category: schema.category,
      enabled: true,
      solo: false,
    },
    structuredClone(schema.defaults),
    overrides
  );
}

export function defaultEnvironment() {
  return {
    domainSizeKm: 5.0,
    maxElevationM: 2600,
    verticalExaggeration: 1.12,
    pedestalEnabled: true,
    pedestalFloorM: -180,

    // Sun (low-angle dramatic Gaea lighting by default so cliffs, strata, boulders & erosion gullies pop with crisp self-shadowing!)
    sunAzimuth: 134,
    sunElevation: 24,
    sunIlluminanceKlux: 118,
    sunTemperatureK: 5550,
    sunAngularRadius: 0.54,
    softShadows: true,
    cloudShadows: true,
    cloudCoverage: 0.32,
    cloudSpeed: 0.15,

    // Sky & Aerial Perspective
    skyEnabled: true,
    rayleigh: 1.08,
    mieTurbidity: 2.3,
    mieAnisotropy: 0.78,
    ozone: 0.95,
    aerialStrength: 0.58,

    // Exponential Height Fog & Valley Mist
    fogEnabled: true,
    fogDensity: 0.18,
    fogHeightFalloff: 0.62,
    fogValleyMist: 0.38,
    fogColor: "#9eb4c9",
    fogInscattering: 0.65,

    // Water Table / Ocean / Alpine Lake
    waterEnabled: true,
    waterLevelM: 135,
    waterShallowColor: "#288582",
    waterDeepColor: "#0a2538",
    waterAbsorption: 0.55,
    waterWaveStrength: 0.48,
    waterFoam: 0.65,

    // Camera & Tone Mapping
    exposureEv: 0.18,
    contrast: 1.1,
    vignette: 0.2,
  };
}

//============================================================================================================================================
//  8 CURATED AAA WORLD PRESETS — TUNED FOR MAXIMUM GEOMORPHOLOGICAL REALISM (CLIFFS, OUTCROPS, BOULDERS, STRATA & DEEP EROSION)
//============================================================================================================================================
export const WORLD_PRESETS = {
  matterhorn: {
    id: "matterhorn",
    name: "Matterhorn Alpine Horn",
    subtitle: "Glaciated pyramidal horn, sheer stratified cliffs, rugged crag outcrops, boulder talus & deep gullies",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 132,
      sunElevation: 23,
      waterEnabled: true,
      waterLevelM: 120,
      fogDensity: 0.18,
      fogValleyMist: 0.42,
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Pennine Thrust Massif",
        elevation: 1680,
        scale: 2.2,
        octaves: 8,
        ridgeSharpness: 1.68,
        cliffSteepness: 0.68,
        strikeAngle: 36,
        anisotropy: 0.4,
        valleyFloor: 0.44,
        warpStrength: 0.45,
        seed: 108,
      }),
      createTerrainLayer("alpine_peak", {
        name: "Central Pyramidal Horn & Cirques",
        blendMode: 3, // Max
        elevation: 2480,
        scale: 2.1,
        ridgeSharpness: 1.92,
        areteCount: 4,
        cirqueCarving: 0.72,
        cliffSteepness: 0.78,
        radiusKm: 2.25,
        warpStrength: 0.38,
        seed: 224,
      }),
      createTerrainLayer("swiss_fbm", {
        name: "Rugged Gneiss Outcrops & Spires",
        blendMode: 0,
        opacity: 0.9,
        elevation: 390,
        scale: 5.5,
        ridgeSharpness: 1.9,
        outcropDensity: 0.78,
        gradientDamping: 0.62,
        maskSlopeMin: 16,
      }),
      createTerrainLayer("strata", {
        name: "Tilted Alpine Cliff Stratification",
        blendMode: 0,
        opacity: 0.85,
        elevation: 290,
        frequency: 17.0,
        dipAngle: 15,
        strikeAngle: 42,
        ledgeSharpness: 0.86,
        maskSlopeMin: 20,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Deep Dendritic Gully & Meltwater Erosion",
        iterations: 90,
        dropletCountK: 120,
        rainRate: 0.023,
        erosionRate: 0.82,
        depositionRate: 0.52,
        sedimentCapacity: 1.7,
        channelSharpness: 0.88,
        gullyDepth: 0.86,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Cliff Talus Cones & Boulder Fields",
        iterations: 42,
        reposeAngle: 35,
        weatheringRate: 0.64,
        talusSpread: 0.76,
        boulderDensity: 0.82,
      }),
      createTerrainLayer("snowfall", {
        name: "Alpine Snowpack & Couloir Avalanches",
        snowlineAlt: 1080,
        snowDepth: 0.72,
        reposeAngle: 42,
        windAzimuth: 305,
        windDrift: 0.54,
        solarMelt: 0.44,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Dark Metamorphic Gneiss Bedrock",
        category: "Bedrock",
        satmapId: "granite_gneiss",
        colPrimary: "#4f565f",
        colSecondary: "#1a1e23",
        colAccent: "#89929e",
        roughness: 0.82,
        strataIntensity: 0.48,
      }),
      createTextureLayer({
        name: "Sheer Stratified Cliff Outcrops",
        category: "Cliffs",
        satmapId: "dolomite_limestone",
        colPrimary: "#857f76",
        colSecondary: "#2b2926",
        colAccent: "#c9c1b4",
        roughness: 0.7,
        strataIntensity: 0.92,
        useSlopeMask: true,
        slopeMin: 30,
        slopeMax: 90,
        slopeFeather: 6,
        useCurvatureMask: true,
        curvatureMode: 0,
        curvatureStrength: 0.65,
      }),
      createTextureLayer({
        name: "Angular Boulder Fields & Talus Scree",
        category: "Sediment",
        satmapId: "talus_scree",
        colPrimary: "#756d62",
        colSecondary: "#302d28",
        colAccent: "#a3998b",
        roughness: 0.88,
        boulderDetail: 0.92,
        useSedimentMask: true,
        sedimentWeight: 0.55,
        talusWeight: 0.95,
        useSlopeMask: true,
        slopeMin: 12,
        slopeMax: 44,
        slopeFeather: 7,
      }),
      createTextureLayer({
        name: "Eroded Gully Channels & Alluvial Gravel",
        category: "Hydrology",
        satmapId: "alluvial_silt",
        colPrimary: "#6e6659",
        colSecondary: "#26231e",
        colAccent: "#9e9380",
        roughness: 0.45,
        specular: 0.55,
        useFlowMask: true,
        flowStrength: 0.88,
      }),
      createTextureLayer({
        name: "Sub-Alpine Valley Meadow & Lichen",
        category: "Biome",
        satmapId: "subalpine_meadow",
        colPrimary: "#4b6935",
        colSecondary: "#1e2e16",
        colAccent: "#799153",
        roughness: 0.88,
        useAltMask: true,
        altMin: 125,
        altMax: 920,
        altFeather: 180,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 29,
        slopeFeather: 6,
        useNoiseMask: true,
        noiseScale: 6.0,
        noiseAmount: 0.36,
      }),
      createTextureLayer({
        name: "Blue Glacial Couloir & Crevasse Ice",
        category: "Snow/Ice",
        satmapId: "glacial_ice",
        colPrimary: "#69a5cc",
        colSecondary: "#214d6e",
        colAccent: "#c4e5f7",
        roughness: 0.24,
        specular: 0.8,
        useAltMask: true,
        altMin: 980,
        altMax: 4500,
        altFeather: 180,
        useCurvatureMask: true,
        curvatureMode: 1,
        curvatureStrength: 0.74,
      }),
      createTextureLayer({
        name: "Fresh Wind-Swept Alpine Snowpack",
        category: "Snow/Ice",
        satmapId: "glacial_snow",
        colPrimary: "#f4f8fc",
        colSecondary: "#a6bdd4",
        colAccent: "#ffffff",
        roughness: 0.36,
        specular: 0.64,
        heightContrast: 0.86,
        useSnowMask: true,
        snowWeight: 0.95,
        useAltMask: true,
        altMin: 940,
        altMax: 4500,
        altFeather: 210,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 46,
        slopeFeather: 8,
      }),
    ],
  },

  grand_canyon: {
    id: "grand_canyon",
    name: "Grand Canyon Stratified Plateau",
    subtitle: "Stepped Colorado sandstone cliffs, bold horizontal stratification, boulder talus & deep gorge",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 146,
      sunElevation: 21,
      sunTemperatureK: 5100,
      fogColor: "#cfa88c",
      fogDensity: 0.14,
      waterEnabled: true,
      waterLevelM: 195,
      waterShallowColor: "#3d7a68",
      waterDeepColor: "#173830",
    }),
    terrainStack: [
      createTerrainLayer("canyon_mesa", {
        name: "Colorado Gorge & Caprock Mesas",
        elevation: 1820,
        scale: 1.85,
        canyonDepth: 0.88,
        canyonWidth: 0.32,
        meanderFreq: 1.8,
        stepCount: 8,
        stepSharpness: 0.86,
        warpStrength: 0.46,
        seed: 311,
      }),
      createTerrainLayer("strata", {
        name: "Paleozoic Cliff Stratification",
        elevation: 380,
        frequency: 19.0,
        dipAngle: 4,
        strikeAngle: 15,
        ledgeSharpness: 0.9,
        foldWarp: 0.24,
        maskSlopeMin: 10,
      }),
      createTerrainLayer("swiss_fbm", {
        name: "Butte & Temple Rock Outcrops",
        elevation: 320,
        scale: 5.2,
        ridgeSharpness: 1.85,
        outcropDensity: 0.76,
        maskSlopeMin: 18,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Side-Canyon Flash Flood Gullies",
        iterations: 90,
        dropletCountK: 120,
        rainRate: 0.021,
        erosionRate: 0.84,
        depositionRate: 0.48,
        channelSharpness: 0.9,
        gullyDepth: 0.88,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Sandstone Cliff Talus & Boulders",
        iterations: 44,
        reposeAngle: 34,
        weatheringRate: 0.65,
        talusSpread: 0.78,
        boulderDensity: 0.85,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Redwall & Supai Sandstone Strata",
        category: "Strata",
        satmapId: "colorado_sandstone",
        colPrimary: "#b85433",
        colSecondary: "#451b10",
        colAccent: "#e6a06b",
        roughness: 0.76,
        strataIntensity: 0.95,
      }),
      createTextureLayer({
        name: "Kaibab & Coconino Pale Cliff Bands",
        category: "Cliffs",
        satmapId: "utah_badlands",
        colPrimary: "#c7a387",
        colSecondary: "#694539",
        colAccent: "#e8d4bf",
        roughness: 0.72,
        strataIntensity: 0.95,
        useAltMask: true,
        altMin: 880,
        altMax: 2600,
        altFeather: 150,
        useSlopeMask: true,
        slopeMin: 26,
        slopeMax: 90,
        slopeFeather: 6,
      }),
      createTextureLayer({
        name: "Boulder Talus Aprons & Red Scree",
        category: "Sediment",
        satmapId: "colorado_sandstone",
        colPrimary: "#8f4329",
        colSecondary: "#38170e",
        colAccent: "#c77d56",
        roughness: 0.88,
        boulderDetail: 0.92,
        useSedimentMask: true,
        sedimentWeight: 0.65,
        talusWeight: 0.95,
        useSlopeMask: true,
        slopeMin: 12,
        slopeMax: 42,
        slopeFeather: 7,
      }),
      createTextureLayer({
        name: "Flash-Flood Arroyo & River Silt",
        category: "Hydrology",
        satmapId: "coastal_sand",
        colPrimary: "#a18e73",
        colSecondary: "#473c2f",
        colAccent: "#d4c5ad",
        roughness: 0.5,
        useFlowMask: true,
        flowStrength: 0.88,
      }),
    ],
  },

  iceland_fjords: {
    id: "iceland_fjords",
    name: "Icelandic Highland Fjords",
    subtitle: "Columnar basalt cliffs, deep braided glacial gullies, black boulder scree & vibrant moss",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 116,
      sunElevation: 20,
      fogDensity: 0.24,
      fogValleyMist: 0.52,
      fogColor: "#93a8ba",
      waterEnabled: true,
      waterLevelM: 150,
      waterShallowColor: "#256e73",
      waterDeepColor: "#091e2b",
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Basalt Fjord Massif",
        elevation: 1750,
        scale: 2.15,
        octaves: 8,
        ridgeSharpness: 1.65,
        cliffSteepness: 0.72,
        strikeAngle: 64,
        anisotropy: 0.48,
        valleyFloor: 0.5,
        warpStrength: 0.48,
        seed: 512,
      }),
      createTerrainLayer("fault_scarp", {
        name: "Rift Valley Cliff Escarpments",
        elevation: 480,
        strikeAngle: 62,
        faultSharpness: 0.88,
        blockScale: 3.0,
        tiltAmount: 0.5,
      }),
      createTerrainLayer("strata", {
        name: "Flood Basalt Trap Bedding",
        elevation: 260,
        frequency: 16.0,
        dipAngle: 8,
        ledgeSharpness: 0.86,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Braided Glacial Gully Incision",
        iterations: 95,
        dropletCountK: 120,
        rainRate: 0.024,
        erosionRate: 0.84,
        depositionRate: 0.54,
        sedimentCapacity: 1.75,
        channelSharpness: 0.88,
        gullyDepth: 0.86,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Black Basalt Boulder Scree",
        iterations: 38,
        reposeAngle: 35,
        weatheringRate: 0.6,
        boulderDensity: 0.85,
      }),
      createTerrainLayer("snowfall", {
        name: "Highland Summit Firn",
        snowlineAlt: 1120,
        snowDepth: 0.62,
        reposeAngle: 42,
        windAzimuth: 280,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Columnar Volcanic Basalt Cliffs",
        category: "Bedrock",
        satmapId: "iceland_basalt",
        colPrimary: "#323840",
        colSecondary: "#121518",
        colAccent: "#5c6673",
        roughness: 0.8,
        strataIntensity: 0.78,
      }),
      createTextureLayer({
        name: "Black Volcanic Sand & Boulder Talus",
        category: "Sediment",
        satmapId: "iceland_basalt",
        colPrimary: "#23272c",
        colSecondary: "#0d0f12",
        colAccent: "#434a52",
        roughness: 0.88,
        boulderDetail: 0.9,
        useSedimentMask: true,
        sedimentWeight: 0.92,
        talusWeight: 0.88,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 38,
        slopeFeather: 7,
      }),
      createTextureLayer({
        name: "Nordic Chartreuse Lichen Moss",
        category: "Biome",
        satmapId: "iceland_moss",
        colPrimary: "#6d8734",
        colSecondary: "#283313",
        colAccent: "#a8bd58",
        roughness: 0.9,
        heightContrast: 0.78,
        useAltMask: true,
        altMin: 165,
        altMax: 980,
        altFeather: 190,
        useSlopeMask: true,
        slopeMin: 3,
        slopeMax: 35,
        slopeFeather: 7,
        useNoiseMask: true,
        noiseScale: 5.8,
        noiseAmount: 0.38,
      }),
      createTextureLayer({
        name: "Glacial Meltwater Channels",
        category: "Hydrology",
        satmapId: "emerald_sediment",
        colPrimary: "#426b6b",
        colSecondary: "#1a2e2e",
        colAccent: "#8abab5",
        roughness: 0.28,
        specular: 0.72,
        useFlowMask: true,
        flowStrength: 0.92,
      }),
      createTextureLayer({
        name: "Highland Summit Snowdrift",
        category: "Snow/Ice",
        satmapId: "glacial_snow",
        colPrimary: "#eef5fc",
        colSecondary: "#9eb6cf",
        colAccent: "#ffffff",
        roughness: 0.38,
        useSnowMask: true,
        snowWeight: 0.95,
      }),
    ],
  },

  karakoram: {
    id: "karakoram",
    name: "Karakoram Jagged Range",
    subtitle: "Towering granite cathedral spires, extreme vertical relief, deep couloirs & boulder moraines",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 138,
      sunElevation: 26,
      waterEnabled: false,
      fogDensity: 0.2,
      fogValleyMist: 0.48,
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Karakoram Batholith Spine",
        elevation: 2350,
        scale: 2.4,
        octaves: 8,
        ridgeSharpness: 1.88,
        cliffSteepness: 0.78,
        strikeAngle: 48,
        anisotropy: 0.52,
        valleyFloor: 0.32,
        warpStrength: 0.48,
        seed: 777,
      }),
      createTerrainLayer("swiss_fbm", {
        name: "Trango Granite Spire Outcrops",
        elevation: 540,
        scale: 5.6,
        ridgeSharpness: 1.95,
        outcropDensity: 0.85,
        gradientDamping: 0.58,
      }),
      createTerrainLayer("strata", {
        name: "Metamorphic Cliff Cleavage",
        elevation: 240,
        frequency: 15.0,
        dipAngle: 22,
        ledgeSharpness: 0.82,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Avalanche Couloir & Glacier Incision",
        iterations: 85,
        dropletCountK: 120,
        rainRate: 0.022,
        erosionRate: 0.8,
        channelSharpness: 0.9,
        gullyDepth: 0.88,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Glacial Moraine Boulder Fields",
        iterations: 38,
        reposeAngle: 37,
        weatheringRate: 0.58,
        boulderDensity: 0.88,
      }),
      createTerrainLayer("snowfall", {
        name: "Himalayan Snowpack & Cornices",
        snowlineAlt: 820,
        snowDepth: 0.82,
        reposeAngle: 44,
        windAzimuth: 295,
        windDrift: 0.58,
        solarMelt: 0.38,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Karakoram Leucogranite Cliffs",
        category: "Bedrock",
        satmapId: "granite_gneiss",
        colPrimary: "#5e646e",
        colSecondary: "#1e2227",
        colAccent: "#98a1ad",
        roughness: 0.74,
        strataIntensity: 0.65,
      }),
      createTextureLayer({
        name: "Glacial Moraine Boulders & Scree",
        category: "Sediment",
        satmapId: "talus_scree",
        colPrimary: "#6b655c",
        colSecondary: "#2c2a26",
        colAccent: "#968e82",
        roughness: 0.88,
        boulderDetail: 0.95,
        useSedimentMask: true,
        sedimentWeight: 0.85,
        talusWeight: 0.92,
      }),
      createTextureLayer({
        name: "Hanging Serac Crevasse Ice",
        category: "Snow/Ice",
        satmapId: "glacial_ice",
        colPrimary: "#609ec7",
        colSecondary: "#1d4666",
        colAccent: "#bfe2f7",
        roughness: 0.22,
        specular: 0.82,
        useCurvatureMask: true,
        curvatureMode: 1,
        curvatureStrength: 0.76,
      }),
      createTextureLayer({
        name: "Deep Himalayan Powder & Cornices",
        category: "Snow/Ice",
        satmapId: "glacial_snow",
        colPrimary: "#f5f9ff",
        colSecondary: "#adc3db",
        colAccent: "#ffffff",
        roughness: 0.36,
        specular: 0.65,
        heightContrast: 0.86,
        useSnowMask: true,
        snowWeight: 0.95,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 47,
        slopeFeather: 9,
      }),
    ],
  },

  caldera_lake: {
    id: "caldera_lake",
    name: "Caldera Crater Lake",
    subtitle: "Collapsed volcanic cone, deep radial pyroclastic gullies, dike outcrops & emerald crater lake",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 122,
      sunElevation: 25,
      waterEnabled: true,
      waterLevelM: 680,
      waterShallowColor: "#1ca39c",
      waterDeepColor: "#062b3d",
      fogDensity: 0.17,
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Volcanic Shield Basement",
        elevation: 860,
        scale: 1.9,
        ridgeSharpness: 1.35,
        valleyFloor: 0.52,
        seed: 401,
      }),
      createTerrainLayer("volcano", {
        name: "Collapsed Summit Caldera",
        blendMode: 3,
        elevation: 2220,
        radiusKm: 2.35,
        calderaRadius: 0.38,
        calderaDepth: 0.72,
        radialGullies: 24,
        gullyDepth: 0.62,
        breachAngle: 135,
        breachStrength: 0.35,
        seed: 419,
      }),
      createTerrainLayer("swiss_fbm", {
        name: "Basaltic Dike & Rim Outcrops",
        elevation: 310,
        scale: 5.4,
        ridgeSharpness: 1.85,
        outcropDensity: 0.75,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Pyroclastic Lahar Gully Erosion",
        iterations: 90,
        dropletCountK: 120,
        rainRate: 0.023,
        erosionRate: 0.82,
        depositionRate: 0.5,
        channelSharpness: 0.88,
        gullyDepth: 0.86,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Caldera Wall Collapse Boulders",
        iterations: 40,
        reposeAngle: 35,
        weatheringRate: 0.6,
        boulderDensity: 0.85,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Dark Andesite & Tephra Cliffs",
        category: "Bedrock",
        satmapId: "iceland_basalt",
        colPrimary: "#363a40",
        colSecondary: "#14161a",
        colAccent: "#606873",
        roughness: 0.82,
        strataIntensity: 0.68,
      }),
      createTextureLayer({
        name: "Hydrothermal Sulfur & Rim Strata",
        category: "Strata",
        satmapId: "volcanic_sulfur",
        colPrimary: "#a3934d",
        colSecondary: "#3d3927",
        colAccent: "#d9c76c",
        roughness: 0.76,
        strataIntensity: 0.85,
        useAltMask: true,
        altMin: 660,
        altMax: 1180,
        altFeather: 140,
        useCurvatureMask: true,
        curvatureMode: 0,
        curvatureStrength: 0.6,
      }),
      createTextureLayer({
        name: "Volcanic Cinder & Boulder Talus",
        category: "Sediment",
        satmapId: "talus_scree",
        colPrimary: "#57524c",
        colSecondary: "#22201d",
        colAccent: "#807a71",
        roughness: 0.9,
        boulderDetail: 0.9,
        useSedimentMask: true,
        sedimentWeight: 0.88,
        talusWeight: 0.9,
      }),
      createTextureLayer({
        name: "Lower Flank Sub-Alpine Pine & Fern",
        category: "Biome",
        satmapId: "subalpine_meadow",
        colPrimary: "#3f5e2c",
        colSecondary: "#182610",
        colAccent: "#6e8f4b",
        roughness: 0.88,
        useAltMask: true,
        altMin: 40,
        altMax: 780,
        altFeather: 190,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 30,
        slopeFeather: 7,
      }),
    ],
  },

  utah_badlands: {
    id: "utah_badlands",
    name: "Utah Badlands & Hoodoos",
    subtitle: "Hyper-dissected Caineville shale badlands, knife-edge rills & colourful banded strata",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 154,
      sunElevation: 22,
      sunTemperatureK: 5250,
      waterEnabled: false,
      fogColor: "#c9ae97",
      fogDensity: 0.14,
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Caineville Mesa Badland Spine",
        elevation: 1580,
        scale: 2.75,
        octaves: 8,
        ridgeSharpness: 1.82,
        cliffSteepness: 0.76,
        strikeAngle: 24,
        anisotropy: 0.35,
        valleyFloor: 0.46,
        warpStrength: 0.5,
        seed: 604,
      }),
      createTerrainLayer("strata", {
        name: "Banded Morrison Formation Beds",
        elevation: 360,
        frequency: 24.0,
        dipAngle: 5,
        strikeAngle: 28,
        ledgeSharpness: 0.9,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Hyper-Dense Badland Rill Erosion",
        iterations: 110,
        dropletCountK: 120,
        rainRate: 0.026,
        erosionRate: 0.92,
        depositionRate: 0.52,
        sedimentCapacity: 1.8,
        channelSharpness: 0.94,
        gullyDepth: 0.92,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Mudstone Pediment Aprons",
        iterations: 34,
        reposeAngle: 34,
        weatheringRate: 0.55,
        boulderDensity: 0.65,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Banded Mancos Clay & Red Shale",
        category: "Strata",
        satmapId: "utah_badlands",
        colPrimary: "#a37362",
        colSecondary: "#422b25",
        colAccent: "#ded0bd",
        roughness: 0.84,
        strataIntensity: 0.96,
      }),
      createTextureLayer({
        name: "Pale Sandstone Hoodoo Caprock",
        category: "Cliffs",
        satmapId: "dolomite_limestone",
        colPrimary: "#c9c0b4",
        colSecondary: "#6b655c",
        colAccent: "#ebe4d8",
        roughness: 0.74,
        strataIntensity: 0.9,
        useCurvatureMask: true,
        curvatureMode: 0,
        curvatureStrength: 0.68,
      }),
      createTextureLayer({
        name: "Outwash Clay Pediment & Fans",
        category: "Sediment",
        satmapId: "alluvial_silt",
        colPrimary: "#9e907b",
        colSecondary: "#4c4439",
        colAccent: "#c7b9a4",
        roughness: 0.88,
        useSedimentMask: true,
        sedimentWeight: 0.94,
        talusWeight: 0.75,
      }),
      createTextureLayer({
        name: "Dry Arroyo Drainage Gullies",
        category: "Hydrology",
        satmapId: "coastal_sand",
        colPrimary: "#bfa98a",
        colSecondary: "#695b49",
        colAccent: "#e0d3be",
        roughness: 0.76,
        useFlowMask: true,
        flowStrength: 0.9,
      }),
    ],
  },

  sahara_erg: {
    id: "sahara_erg",
    name: "Sahara Erg & Inselbergs",
    subtitle: "Stratified sandstone inselberg cliffs & boulder outcrops rising from golden wind-rippled dunes",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 138,
      sunElevation: 20,
      sunTemperatureK: 4950,
      waterEnabled: false,
      fogColor: "#deb98e",
      fogDensity: 0.2,
      mieTurbidity: 3.5,
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Tassili Sandstone Inselbergs",
        elevation: 1420,
        scale: 2.25,
        ridgeSharpness: 1.78,
        cliffSteepness: 0.82,
        valleyFloor: 0.68,
        warpStrength: 0.48,
        seed: 902,
      }),
      createTerrainLayer("strata", {
        name: "Wind-Abraded Sandstone Strata",
        elevation: 310,
        frequency: 18.0,
        dipAngle: 6,
        ledgeSharpness: 0.88,
      }),
      createTerrainLayer("swiss_fbm", {
        name: "Craggy Desert Rock Outcrops",
        elevation: 340,
        scale: 5.5,
        ridgeSharpness: 1.9,
        outcropDensity: 0.82,
        maskAltMin: 280,
      }),
      createTerrainLayer("dune_sea", {
        name: "Grand Erg Transverse Sand Dunes",
        blendMode: 0,
        elevation: 420,
        scale: 4.8,
        windAngle: 44,
        crestSharpness: 1.8,
        asymmetry: 0.68,
        rippleDetail: 0.48,
        maskAltMin: -200,
        maskAltMax: 950,
        maskSlopeMax: 35,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Cliff-Base Boulders & Sand Slip-Faces",
        iterations: 32,
        reposeAngle: 33,
        weatheringRate: 0.54,
        boulderDensity: 0.82,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Golden Aeolian Silica Dunes",
        category: "Sediment",
        satmapId: "sahara_erg",
        colPrimary: "#d1a269",
        colSecondary: "#754c29",
        colAccent: "#f2dba8",
        roughness: 0.72,
        detailScale: 24.0,
      }),
      createTextureLayer({
        name: "Desert-Varnished Stratified Cliffs",
        category: "Bedrock",
        satmapId: "colorado_sandstone",
        colPrimary: "#733a27",
        colSecondary: "#24100a",
        colAccent: "#ad6244",
        roughness: 0.74,
        strataIntensity: 0.92,
        boulderDetail: 0.85,
        useAltMask: true,
        altMin: 360,
        altMax: 2500,
        altFeather: 130,
        useSlopeMask: true,
        slopeMin: 20,
        slopeMax: 90,
        slopeFeather: 6,
      }),
      createTextureLayer({
        name: "Wind-Rippled Dune Crest Sand",
        category: "Sediment",
        satmapId: "sahara_erg",
        colPrimary: "#efd6a5",
        colSecondary: "#ba8b54",
        colAccent: "#fff2d4",
        roughness: 0.62,
        useCurvatureMask: true,
        curvatureMode: 0,
        curvatureStrength: 0.65,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 28,
        slopeFeather: 6,
      }),
    ],
  },

  scottish_glen: {
    id: "scottish_glen",
    name: "Scottish Glen & Loch",
    subtitle: "Glaciated U-shaped highland valley, rugged gabbro crag outcrops, boulder scree & loch",
    env: Object.assign(defaultEnvironment(), {
      sunAzimuth: 124,
      sunElevation: 22,
      waterEnabled: true,
      waterLevelM: 185,
      waterShallowColor: "#2c574f",
      waterDeepColor: "#0b1c24",
      fogDensity: 0.22,
      fogValleyMist: 0.48,
    }),
    terrainStack: [
      createTerrainLayer("mountain_range", {
        name: "Glen Coe Glaciated Munros",
        elevation: 1680,
        scale: 2.05,
        ridgeSharpness: 1.58,
        cliffSteepness: 0.7,
        strikeAngle: 52,
        anisotropy: 0.45,
        valleyFloor: 0.52,
        warpStrength: 0.46,
        seed: 818,
      }),
      createTerrainLayer("swiss_fbm", {
        name: "Highland Gabbro Crag Outcrops",
        elevation: 390,
        scale: 5.0,
        ridgeSharpness: 1.82,
        outcropDensity: 0.8,
        gradientDamping: 0.65,
      }),
      createTerrainLayer("strata", {
        name: "Rhyolite Sill Cliff Bands",
        elevation: 240,
        frequency: 15.0,
        dipAngle: 10,
        ledgeSharpness: 0.82,
      }),
      createTerrainLayer("hydraulic_erosion", {
        name: "Highland Burn & Waterfall Gullies",
        iterations: 90,
        dropletCountK: 120,
        rainRate: 0.023,
        erosionRate: 0.8,
        depositionRate: 0.5,
        channelSharpness: 0.86,
        gullyDepth: 0.85,
      }),
      createTerrainLayer("thermal_erosion", {
        name: "Glen Boulder Scree Aprons",
        iterations: 38,
        reposeAngle: 35,
        weatheringRate: 0.58,
        boulderDensity: 0.85,
      }),
    ],
    textureStack: [
      createTextureLayer({
        name: "Highland Granite & Gabbro Crags",
        category: "Bedrock",
        satmapId: "granite_gneiss",
        colPrimary: "#54585e",
        colSecondary: "#1e2125",
        colAccent: "#888e96",
        roughness: 0.78,
        strataIntensity: 0.72,
      }),
      createTextureLayer({
        name: "Boulder Scree & Talus Cones",
        category: "Sediment",
        satmapId: "talus_scree",
        colPrimary: "#6e675d",
        colSecondary: "#2e2b27",
        colAccent: "#999083",
        roughness: 0.88,
        boulderDetail: 0.92,
        useSedimentMask: true,
        sedimentWeight: 0.7,
        talusWeight: 0.95,
      }),
      createTextureLayer({
        name: "Peat Bog & Heather Moorland",
        category: "Biome",
        satmapId: "scottish_heather",
        colPrimary: "#664e35",
        colSecondary: "#281e15",
        colAccent: "#8c704c",
        roughness: 0.9,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 34,
        slopeFeather: 8,
      }),
      createTextureLayer({
        name: "Bracken & Glen Pasture Turf",
        category: "Biome",
        satmapId: "subalpine_meadow",
        colPrimary: "#4d6932",
        colSecondary: "#1e2d13",
        colAccent: "#7d9652",
        roughness: 0.88,
        useAltMask: true,
        altMin: 190,
        altMax: 780,
        altFeather: 160,
        useSlopeMask: true,
        slopeMin: 0,
        slopeMax: 25,
        slopeFeather: 6,
        useNoiseMask: true,
        noiseScale: 5.5,
        noiseAmount: 0.38,
      }),
    ],
  },
};
