/**
 * 3D Mesh Exporters for Geological Cliff Models (OBJ, PLY, glTF/GLB JSON)
 */

import { MeshData } from './types';

export class MeshExporter {
  /**
   * Export to standard Wavefront OBJ format
   */
  public static toOBJ(mesh: MeshData, modelName: string = 'GeologicalCliff'): string {
    const { vertices, indices, normals, colors, strataIndices } = mesh;
    let obj = `# Geological Cliff Formation Generator (Non-Noise Procedural Geology Engine)\n`;
    obj += `# Model Name: ${modelName}\n`;
    obj += `# Vertices: ${mesh.vertexCount}\n`;
    obj += `# Triangles: ${mesh.triangleCount}\n\n`;

    obj += `o ${modelName}\n\n`;

    // Write vertices (with optional vertex colors as RGB extensions)
    for (let i = 0; i < vertices.length; i += 3) {
      const x = vertices[i].toFixed(5);
      const y = vertices[i + 1].toFixed(5);
      const z = vertices[i + 2].toFixed(5);
      if (colors && colors.length > i + 2) {
        const r = colors[i].toFixed(4);
        const g = colors[i + 1].toFixed(4);
        const b = colors[i + 2].toFixed(4);
        obj += `v ${x} ${y} ${z} ${r} ${g} ${b}\n`;
      } else {
        obj += `v ${x} ${y} ${z}\n`;
      }
    }

    obj += `\n`;

    // Write vertex normals
    if (normals && normals.length > 0) {
      for (let i = 0; i < normals.length; i += 3) {
        const nx = normals[i].toFixed(5);
        const ny = normals[i + 1].toFixed(5);
        const nz = normals[i + 2].toFixed(5);
        obj += `vn ${nx} ${ny} ${nz}\n`;
      }
      obj += `\n`;
    }

    // Write faces (1-indexed triangles, strictly 3 vertices per face)
    const hasNormals = normals && normals.length === vertices.length;

    let currentStrata = -1;
    for (let i = 0; i < indices.length; i += 3) {
      const i0 = indices[i] + 1;
      const i1 = indices[i + 1] + 1;
      const i2 = indices[i + 2] + 1;

      if (strataIndices) {
        const s = strataIndices[indices[i]];
        if (s !== currentStrata) {
          currentStrata = s;
          obj += `g Strata_Layer_${currentStrata}\n`;
        }
      }

      if (hasNormals) {
        obj += `f ${i0}//${i0} ${i1}//${i1} ${i2}//${i2}\n`;
      } else {
        obj += `f ${i0} ${i1} ${i2}\n`;
      }
    }

    return obj;
  }

  /**
   * Export to Stanford PLY format
   */
  public static toPLY(mesh: MeshData): string {
    const { vertices, indices, normals, colors } = mesh;
    const numVertices = vertices.length / 3;
    const numFaces = indices.length / 3;
    const hasColors = colors && colors.length === vertices.length;

    let ply = `ply\n`;
    ply += `format ascii 1.0\n`;
    ply += `comment Generated by Geological Cliff Formation Engine\n`;
    ply += `element vertex ${numVertices}\n`;
    ply += `property float x\n`;
    ply += `property float y\n`;
    ply += `property float z\n`;
    ply += `property float nx\n`;
    ply += `property float ny\n`;
    ply += `property float nz\n`;
    if (hasColors) {
      ply += `property uchar red\n`;
      ply += `property uchar green\n`;
      ply += `property uchar blue\n`;
    }
    ply += `element face ${numFaces}\n`;
    ply += `property list uchar int vertex_indices\n`;
    ply += `end_header\n`;

    for (let i = 0; i < numVertices; i++) {
      const x = vertices[i * 3].toFixed(5);
      const y = vertices[i * 3 + 1].toFixed(5);
      const z = vertices[i * 3 + 2].toFixed(5);
      const nx = (normals ? normals[i * 3] : 0).toFixed(5);
      const ny = (normals ? normals[i * 3 + 1] : 0).toFixed(5);
      const nz = (normals ? normals[i * 3 + 2] : 1).toFixed(5);

      if (hasColors && colors) {
        const r = Math.round(colors[i * 3] * 255);
        const g = Math.round(colors[i * 3 + 1] * 255);
        const b = Math.round(colors[i * 3 + 2] * 255);
        ply += `${x} ${y} ${z} ${nx} ${ny} ${nz} ${r} ${g} ${b}\n`;
      } else {
        ply += `${x} ${y} ${z} ${nx} ${ny} ${nz}\n`;
      }
    }

    for (let i = 0; i < indices.length; i += 3) {
      ply += `3 ${indices[i]} ${indices[i + 1]} ${indices[i + 2]}\n`;
    }

    return ply;
  }
}
