/**
 * Authentic Geological Presets for Procedural Cliff Generator
 * All presets strictly satisfy the zero-noise structural geology constraints.
 */

import { CliffConfig } from './types';

export const GEOLOGICAL_PRESETS: Record<string, { name: string; description: string; config: CliffConfig }> = {
  sedimentary_canyon: {
    name: 'Sedimentary Canyon Wall (Grand Canyon / Zion)',
    description: 'Prominent horizontal bedding strata, alternating hard sandstone ledges and soft shale benches, orthogonal vertical jointing, caprock overhangs, and talus apron.',
    config: {
      seed: 42,
      formationType: 'sedimentary_canyon',
      width: 40,
      height: 35,
      depth: 25,
      strataCount: 8,
      overallDip: 3.5,
      talusHeightFraction: 0.22,
      buttressCount: 3,
      overhangIntensity: 1.35,
      cutCount: 12,
      maxCutOffset: 0.28,
      shearFacetSharpness: 0.85,
      jointSetsCount: 3,
      jointSpacing: 4.5,
      jointDilation: 0.08,
      staggerJoints: true,
      edgeChipCount: 24,
      edgeChipDepth: 0.8,
      sdfResolution: 64,
      erosionStrength: 0.75,
      strataHardnessContrast: 0.8,
      smoothMinRadius: 0.15,
      surfaceCrackDensity: 0.7,
      crackMaxDepthOffset: 0.05,
      crackBranching: true,
      crackChippingIntensity: 0.65,
      finalLaplacianSmoothing: 0.35,
    },
  },

  granite_scarp: {
    name: 'Massive Granite Batholith Scarp (Yosemite / El Capitan)',
    description: 'Massive monolithic crystalline rock, prominent vertical buttresses, sheet exfoliation fractures, steep planar shear facets, and high mechanical competence.',
    config: {
      seed: 108,
      formationType: 'granite_scarp',
      width: 38,
      height: 45,
      depth: 28,
      strataCount: 3,
      overallDip: 1.0,
      talusHeightFraction: 0.15,
      buttressCount: 4,
      overhangIntensity: 1.15,
      cutCount: 16,
      maxCutOffset: 0.35,
      shearFacetSharpness: 0.95,
      jointSetsCount: 2,
      jointSpacing: 7.5,
      jointDilation: 0.06,
      staggerJoints: false,
      edgeChipCount: 18,
      edgeChipDepth: 0.9,
      sdfResolution: 64,
      erosionStrength: 0.45,
      strataHardnessContrast: 0.3,
      smoothMinRadius: 0.2,
      surfaceCrackDensity: 0.5,
      crackMaxDepthOffset: 0.04,
      crackBranching: true,
      crackChippingIntensity: 0.5,
      finalLaplacianSmoothing: 0.4,
    },
  },

  columnar_basalt: {
    name: 'Columnar Basalt Formation (Giants Causeway / Fingals)',
    description: 'Volcanic thermal contraction joints producing dense vertical polygonal column tiers, stepped fracture benches, and crisp faceted block faces.',
    config: {
      seed: 256,
      formationType: 'columnar_basalt',
      width: 35,
      height: 32,
      depth: 22,
      strataCount: 5,
      overallDip: 0.0,
      talusHeightFraction: 0.18,
      buttressCount: 2,
      overhangIntensity: 1.05,
      cutCount: 10,
      maxCutOffset: 0.22,
      shearFacetSharpness: 0.9,
      jointSetsCount: 3,
      jointSpacing: 2.8,
      jointDilation: 0.1,
      staggerJoints: true,
      edgeChipCount: 30,
      edgeChipDepth: 0.65,
      sdfResolution: 64,
      erosionStrength: 0.55,
      strataHardnessContrast: 0.4,
      smoothMinRadius: 0.1,
      surfaceCrackDensity: 0.8,
      crackMaxDepthOffset: 0.045,
      crackBranching: false,
      crackChippingIntensity: 0.7,
      finalLaplacianSmoothing: 0.25,
    },
  },

  alpine_fault: {
    name: 'Alpine Tectonic Fault Scarp (Dolomites / Rockies)',
    description: 'Tectonic uplift scarp with steep fault planes, jagged faceted dihedral notches, heavy talus scree ramp, and conjugate shear jointing.',
    config: {
      seed: 777,
      formationType: 'alpine_fault',
      width: 42,
      height: 40,
      depth: 26,
      strataCount: 6,
      overallDip: 8.5,
      talusHeightFraction: 0.30,
      buttressCount: 3,
      overhangIntensity: 1.25,
      cutCount: 18,
      maxCutOffset: 0.32,
      shearFacetSharpness: 0.9,
      jointSetsCount: 3,
      jointSpacing: 4.0,
      jointDilation: 0.09,
      staggerJoints: true,
      edgeChipCount: 26,
      edgeChipDepth: 0.85,
      sdfResolution: 64,
      erosionStrength: 0.8,
      strataHardnessContrast: 0.75,
      smoothMinRadius: 0.12,
      surfaceCrackDensity: 0.75,
      crackMaxDepthOffset: 0.055,
      crackBranching: true,
      crackChippingIntensity: 0.8,
      finalLaplacianSmoothing: 0.3,
    },
  },

  coastal_bluff: {
    name: 'Coastal Wave-Cut Sea Cliff (White Cliffs / Pacific Scarp)',
    description: 'Marine hydraulic weathering producing a basal wave-cut notch, sheer vertical scarp wall, overhang cornice, and tensile unloading fissures.',
    config: {
      seed: 512,
      formationType: 'coastal_bluff',
      width: 36,
      height: 34,
      depth: 24,
      strataCount: 7,
      overallDip: 2.0,
      talusHeightFraction: 0.12,
      buttressCount: 2,
      overhangIntensity: 1.45,
      cutCount: 14,
      maxCutOffset: 0.26,
      shearFacetSharpness: 0.85,
      jointSetsCount: 2,
      jointSpacing: 3.8,
      jointDilation: 0.08,
      staggerJoints: true,
      edgeChipCount: 22,
      edgeChipDepth: 0.75,
      sdfResolution: 64,
      erosionStrength: 0.9,
      strataHardnessContrast: 0.85,
      smoothMinRadius: 0.18,
      surfaceCrackDensity: 0.65,
      crackMaxDepthOffset: 0.05,
      crackBranching: true,
      crackChippingIntensity: 0.6,
      finalLaplacianSmoothing: 0.35,
    },
  },
};
